version: '3.0'
services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
    command: --config /oauth2-proxy.cfg
    ports:
      - 4180:4180/tcp
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    networks:
      dex: {}
      frontend: {}
    depends_on:
      - dex
      - frontend
  
  dex:
    container_name: dex
    image: quay.io/dexidp/dex:v2.23.0
    command: serve /dex.yaml
    ports:
      - 4190:4190/tcp
    hostname: dex
    volumes:
      - "./dex.yaml:/dex.yaml"
    restart: unless-stopped
    networks:
      dex:
        aliases:
          - dex.localhost
      etcd: {}
    depends_on:
      - etcd
    env_file:
      - ./microsoft.env

  frontend:
    container_name: frontend
    image: frontend-local
    networks:
      frontend: {}
      
  etcd:
    container_name: etcd
    image: gcr.io/etcd-development/etcd:v3.4.7
    entrypoint: /usr/local/bin/etcd
    command:
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
    networks:
      etcd: {}

networks:
  dex: {}
  etcd: {}
  frontend: {}