/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package security;

import java.security.Key;
import java.security.KeyPair;

import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.io.Encoders;
import io.jsonwebtoken.security.Keys;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        KeyPair keyPair = Keys.keyPairFor(SignatureAlgorithm.RS256);
        String privateKey = Encoders.BASE64.encode(keyPair.getPrivate().getEncoded());
        String publicKey = Encoders.BASE64.encode(keyPair.getPublic().getEncoded());
        System.out.println("Private: " + privateKey);
        System.out.println("Public: " + publicKey);
    }
}
